-- DecodEbook — public schema, AUTHORITATIVE source of truth.
-- Generated by `pg_dump --schema-only --schema=public --no-owner` from LIVE PRODUCTION
-- (Supabase project rtrpqgywnuemipuylmnz) on 2026-09-13. Supersedes the prior hand-maintained
-- snapshot. NOTE: Storage bucket + policies ('book-media') live in the storage schema, defined in
-- sql/026 — they are NOT part of this public-schema dump. The two pg_dump `\restrict/\unrestrict`
-- psql directives were stripped so this also runs in the Supabase SQL editor.
--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: add_bonus_credits(uuid, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.add_bonus_credits(p_user_id uuid, p_credits integer) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
begin
  insert into public.bonus_credits (user_id, balance, updated_at)
  values (p_user_id, p_credits, now())
  on conflict (user_id) do update set balance = bonus_credits.balance + p_credits, updated_at = now();
  insert into public.credit_ledger (user_id, delta, type, reason)
  values (p_user_id, p_credits, 'bonus', 'Referral / bonus credits');
end; $$;


--
-- Name: add_pack_credits(uuid, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.add_pack_credits(p_user_id uuid, p_credits integer) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
  UPDATE subscriptions
     SET pack_credits_balance   = COALESCE(pack_credits_balance, 0)   + p_credits,
         pack_credits_purchased = COALESCE(pack_credits_purchased, 0) + p_credits,
         updated_at = now()
   WHERE user_id = p_user_id AND status IN ('active', 'trialing');
  INSERT INTO public.credit_ledger (user_id, delta, type, reason)
  VALUES (p_user_id, p_credits, 'purchase', 'Credit pack');
END;
$$;


--
-- Name: award_referral_on_engagement(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.award_referral_on_engagement(p_referred uuid) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_id            bigint;
  v_referrer      uuid;
  v_ip_hash       text;
  v_email_ok      timestamptz;
  v_used          int;
  v_credited      int;
  v_referred_norm text;
  v_referrer_norm text;
  threshold constant int := 20;   -- free credits the referred user must spend to qualify (tunable)
BEGIN
  -- Pending (not-yet-processed) referral for this user?
  SELECT id, referrer_id, referred_ip_hash
    INTO v_id, v_referrer, v_ip_hash
    FROM referral_signups
   WHERE referred_user_id = p_referred AND activated = false
   LIMIT 1;
  IF v_id IS NULL THEN RETURN; END IF;

  -- (1) email verified
  SELECT email_confirmed_at INTO v_email_ok FROM auth.users WHERE id = p_referred;
  IF v_email_ok IS NULL THEN RETURN; END IF;   -- not yet verified; try again on later usage

  -- (2) genuine free-credit usage
  SELECT COALESCE(SUM(credits_cost), 0) INTO v_used FROM usage_logs WHERE user_id = p_referred;
  IF v_used < threshold THEN RETURN; END IF;    -- not engaged enough yet; try again later

  -- (NEW) one PERSON per canonical inbox: block self-referral-by-email and a second account whose
  -- normalized email matches an already-credited referral of the same referrer.
  SELECT normalize_email(email) INTO v_referred_norm FROM auth.users WHERE id = p_referred;
  SELECT normalize_email(email) INTO v_referrer_norm FROM auth.users WHERE id = v_referrer;
  IF v_referred_norm IS NOT NULL AND (
        v_referred_norm = v_referrer_norm
     OR EXISTS (
          SELECT 1 FROM referral_signups s2
            JOIN auth.users u2 ON u2.id = s2.referred_user_id
           WHERE s2.referrer_id = v_referrer
             AND s2.referred_user_id <> p_referred
             AND s2.referrer_credited = true
             AND normalize_email(u2.email) = v_referred_norm
        )
  ) THEN
    UPDATE referral_signups SET activated = true, referrer_credited = false WHERE id = v_id;
    RETURN;
  END IF;

  -- (6) same-IP self-farm guard: another already-credited referral by this referrer shares this IP
  IF v_ip_hash IS NOT NULL AND EXISTS (
    SELECT 1 FROM referral_signups s2
     WHERE s2.referrer_id = v_referrer
       AND s2.referred_user_id <> p_referred
       AND s2.referred_ip_hash = v_ip_hash
       AND s2.referrer_credited = true
  ) THEN
    UPDATE referral_signups SET activated = true, referrer_credited = false WHERE id = v_id;
    RETURN;
  END IF;

  -- (4) per-referrer cap: 1,000 credits = 10 x 100
  SELECT count(*) INTO v_credited FROM referral_signups
   WHERE referrer_id = v_referrer AND referrer_credited = true;

  -- Mark processed once; credit only under the cap.
  UPDATE referral_signups
     SET activated = true, referrer_credited = (v_credited < 10)
   WHERE id = v_id;

  IF v_credited < 10 THEN
    PERFORM add_bonus_credits(v_referrer, 100);   -- also writes a credit_ledger 'bonus' row (015)
  END IF;
END;
$$;


--
-- Name: credit_period_start(uuid, text, timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.credit_period_start(p_user_id uuid, p_tier text, p_sub_start timestamp with time zone) RETURNS timestamp with time zone
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE v timestamptz;
BEGIN
  IF p_tier = 'free' THEN
    SELECT first_seen_at INTO v FROM profiles WHERE id = p_user_id;
    RETURN COALESCE(v, '1970-01-01'::timestamptz);
  END IF;
  RETURN COALESCE(p_sub_start, date_trunc('month', now()));
END;
$$;


--
-- Name: deplete_wallet_on_usage(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.deplete_wallet_on_usage() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_tier         text := 'free';
  v_sub_start    timestamptz;
  v_monthly      int;
  v_period_start timestamptz;
  v_prior_used   int;
  v_from_monthly int;
  v_overflow     int;
  v_pack         int := 0;
  v_bonus        int := 0;
  v_take         int;
BEGIN
  IF COALESCE(NEW.credits_cost, 0) <= 0 THEN RETURN NEW; END IF;

  SELECT tier, current_period_start, COALESCE(pack_credits_balance, 0)
    INTO v_tier, v_sub_start, v_pack
    FROM subscriptions
   WHERE user_id = NEW.user_id AND status IN ('active', 'trialing')
   ORDER BY created_at DESC
   LIMIT 1;
  IF v_tier IS NULL THEN v_tier := 'free'; END IF;

  v_monthly := tier_monthly_credits(v_tier);
  IF v_monthly IS NULL THEN RETURN NEW; END IF;         -- unmetered tier

  v_period_start := credit_period_start(NEW.user_id, v_tier, v_sub_start);

  -- Usage in this period BEFORE this row. This is an AFTER trigger, so NEW is already
  -- counted in the SUM — subtract it back out to get the prior total.
  SELECT COALESCE(SUM(credits_cost), 0) - NEW.credits_cost
    INTO v_prior_used
    FROM usage_logs
   WHERE user_id = NEW.user_id AND created_at >= v_period_start;
  IF v_prior_used < 0 THEN v_prior_used := 0; END IF;

  v_from_monthly := LEAST(NEW.credits_cost, GREATEST(0, v_monthly - v_prior_used));
  v_overflow := NEW.credits_cost - v_from_monthly;
  IF v_overflow <= 0 THEN RETURN NEW; END IF;           -- fully covered by monthly

  -- Bonus first: it's temporary/free, so drain it before the paid packs.
  SELECT COALESCE(balance, 0) INTO v_bonus FROM bonus_credits WHERE user_id = NEW.user_id;
  IF v_bonus > 0 THEN
    v_take := LEAST(v_overflow, v_bonus);
    UPDATE bonus_credits
       SET balance = balance - v_take, updated_at = now()
     WHERE user_id = NEW.user_id;
    v_overflow := v_overflow - v_take;
  END IF;

  -- Then packs (paid, never expire — preserved for last).
  IF v_overflow > 0 AND v_pack > 0 THEN
    v_take := LEAST(v_overflow, v_pack);
    UPDATE subscriptions
       SET pack_credits_balance = COALESCE(pack_credits_balance, 0) - v_take,
           updated_at = now()
     WHERE user_id = NEW.user_id AND status IN ('active', 'trialing');
    v_overflow := v_overflow - v_take;
  END IF;

  -- Any remaining v_overflow means the pre-charge gate let an over-budget action
  -- through; it is intentionally not clamped here (history stays truthful).
  RETURN NEW;
END;
$$;


--
-- Name: end_session(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.end_session(p_session_id uuid) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
begin
  update public.sessions
    set ended_at = now(),
        duration_seconds = extract(epoch from (now() - started_at))::int
  where id = p_session_id
    and user_id = auth.uid();
end;
$$;


--
-- Name: get_or_create_referral_code(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_or_create_referral_code(p_user_id uuid) RETURNS text
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_code TEXT;
BEGIN
  SELECT code INTO v_code FROM referral_codes WHERE user_id = p_user_id;
  IF v_code IS NOT NULL THEN RETURN v_code; END IF;

  v_code := substr(md5(random()::text || p_user_id::text || now()::text), 1, 8);
  INSERT INTO referral_codes (user_id, code) VALUES (p_user_id, v_code)
  ON CONFLICT (user_id) DO NOTHING;

  SELECT code INTO v_code FROM referral_codes WHERE user_id = p_user_id;
  RETURN v_code;
END;
$$;


--
-- Name: get_referral_stats(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_referral_stats(p_user_id uuid) RETURNS json
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_code TEXT;
  v_clicks INT;
  v_click_credits INT;
  v_signups INT;
  v_activated INT;
  v_signup_credits INT;
  v_bonus INT;
BEGIN
  SELECT code INTO v_code FROM referral_codes WHERE user_id = p_user_id;

  SELECT COUNT(*) INTO v_clicks FROM referral_clicks
    WHERE referrer_id = p_user_id AND credited = true;
  v_click_credits := LEAST(v_clicks * 5, 50);

  SELECT COUNT(*) INTO v_signups FROM referral_signups
    WHERE referrer_id = p_user_id;
  SELECT COUNT(*) INTO v_activated FROM referral_signups
    WHERE referrer_id = p_user_id AND activated = true AND referrer_credited = true;
  v_signup_credits := v_activated * 100;

  SELECT COALESCE(balance, 0) INTO v_bonus FROM bonus_credits WHERE user_id = p_user_id;

  RETURN json_build_object(
    'code', v_code,
    'clicks', v_clicks,
    'click_credits', v_click_credits,
    'click_credits_cap', 50,
    'signups', v_signups,
    'activated', v_activated,
    'signup_credits', v_signup_credits,
    'bonus_balance', COALESCE(v_bonus, 0),
    'total_earned', v_click_credits + v_signup_credits
  );
END;
$$;


--
-- Name: get_user_credits(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_user_credits(p_user_id uuid) RETURNS json
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_tier         text := 'free';
  v_period_start timestamptz;
  v_period_end   timestamptz;
  v_cancel       boolean := false;
  v_pack_balance int := 0;
  v_pack_bought  int := 0;
  v_bonus        int := 0;
  v_credits_used int;
  v_monthly      int;
BEGIN
  SELECT tier, current_period_start, current_period_end, cancel_at_period_end,
         COALESCE(pack_credits_balance, 0), COALESCE(pack_credits_purchased, 0)
    INTO v_tier, v_period_start, v_period_end, v_cancel, v_pack_balance, v_pack_bought
    FROM public.subscriptions
   WHERE user_id = p_user_id AND status IN ('active', 'trialing')
   ORDER BY created_at DESC
   LIMIT 1;

  IF v_tier IS NULL THEN v_tier := 'free'; END IF;

  IF v_tier = 'free' THEN
    SELECT first_seen_at INTO v_period_start FROM public.profiles WHERE id = p_user_id;
    v_period_start := COALESCE(v_period_start, '1970-01-01'::timestamptz);
    v_period_end := NULL;
  ELSIF v_period_start IS NULL THEN
    v_period_start := date_trunc('month', now());
  END IF;

  SELECT COALESCE(balance, 0) INTO v_bonus FROM public.bonus_credits WHERE user_id = p_user_id;

  SELECT COALESCE(SUM(credits_cost), 0) INTO v_credits_used
    FROM public.usage_logs
   WHERE user_id = p_user_id AND created_at >= v_period_start;

  -- Cap monthly usage at the allowance; over-monthly overflow is accounted in the wallet.
  v_monthly := tier_monthly_credits(v_tier);
  IF v_monthly IS NOT NULL AND v_credits_used > v_monthly THEN
    v_credits_used := v_monthly;
  END IF;

  RETURN json_build_object(
    'tier', v_tier,
    'period_start', v_period_start,
    'period_end', v_period_end,
    'cancel_at_period_end', v_cancel,
    'credits_used', v_credits_used,
    'pack_credits', v_pack_balance,
    'pack_purchased', v_pack_bought,
    'bonus_credits', COALESCE(v_bonus, 0)
  );
END;
$$;


--
-- Name: get_user_tier_and_usage(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_user_tier_and_usage(p_user_id uuid) RETURNS json
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
declare
  v_tier text := 'free';
  v_period_start timestamptz;
  v_period_end timestamptz;
  v_cancel boolean := false;
  v_text_count int;
  v_tts_count int;
  v_image_count int;
  v_video_count int;
  v_chat_count int;
begin
  select tier, current_period_start, current_period_end, cancel_at_period_end
    into v_tier, v_period_start, v_period_end, v_cancel
  from subscriptions
  where user_id = p_user_id and status in ('active', 'trialing')
  order by created_at desc limit 1;

  if v_tier is null then v_tier := 'free'; end if;
  if v_period_start is null then v_period_start := date_trunc('month', now()); end if;

  select
    coalesce(sum(case when action like 'text:%' or action in (
      'analyzeBookStructure','extractChapterText','extractConcepts',
      'extractDictionary','podcastScript','videoPrompt'
    ) then 1 else 0 end), 0),
    coalesce(sum(case when action in ('tts','podcastAudio') then 1 else 0 end), 0),
    coalesce(sum(case when action = 'generateImage' then 1 else 0 end), 0),
    coalesce(sum(case when action in ('videoVeo','videoSeedance') then 1 else 0 end), 0),
    coalesce(sum(case when action = 'chat' then 1 else 0 end), 0)
  into v_text_count, v_tts_count, v_image_count, v_video_count, v_chat_count
  from usage_logs
  where user_id = p_user_id and created_at >= v_period_start;

  return json_build_object(
    'tier', v_tier,
    'period_start', v_period_start,
    'period_end', v_period_end,
    'cancel_at_period_end', v_cancel,
    'text_used', v_text_count,
    'tts_used', v_tts_count,
    'image_used', v_image_count,
    'video_used', v_video_count,
    'chat_used', v_chat_count
  );
end;
$$;


--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
begin
  insert into public.profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;


--
-- Name: increment_generation_count(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.increment_generation_count() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
begin
  if new.status = 'success' then
    update public.profiles
      set total_generations = total_generations + 1
    where id = new.user_id;
  end if;
  return new;
end;
$$;


--
-- Name: normalize_email(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.normalize_email(e text) RETURNS text
    LANGUAGE sql IMMUTABLE
    SET search_path TO 'public', 'pg_temp'
    AS $$
  SELECT CASE
    WHEN e IS NULL OR position('@' in e) = 0 THEN NULL
    ELSE (
      WITH p AS (
        SELECT split_part(lower(trim(e)), '@', 1) AS loc,
               split_part(lower(trim(e)), '@', 2) AS dom
      )
      SELECT CASE
        WHEN dom IN ('gmail.com', 'googlemail.com')
          THEN regexp_replace(split_part(loc, '+', 1), '\.', '', 'g') || '@gmail.com'
        ELSE split_part(loc, '+', 1) || '@' || dom
      END
      FROM p
    )
  END;
$$;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


--
-- Name: start_session(text, text, text, integer, integer, text, boolean); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.start_session(p_device_type text DEFAULT NULL::text, p_os text DEFAULT NULL::text, p_browser text DEFAULT NULL::text, p_screen_width integer DEFAULT NULL::integer, p_screen_height integer DEFAULT NULL::integer, p_referrer text DEFAULT NULL::text, p_is_pwa boolean DEFAULT false) RETURNS uuid
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare
  v_session_id uuid;
begin
  insert into public.sessions (user_id, device_type, os, browser, screen_width, screen_height, referrer, is_pwa)
  values (auth.uid(), p_device_type, p_os, p_browser, p_screen_width, p_screen_height, p_referrer, p_is_pwa)
  returning id into v_session_id;

  update public.profiles set last_active_at = now() where id = auth.uid();

  return v_session_id;
end;
$$;


--
-- Name: tier_monthly_credits(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.tier_monthly_credits(p_tier text) RETURNS integer
    LANGUAGE sql IMMUTABLE
    AS $$
  SELECT CASE p_tier
           WHEN 'pro' THEN 1000
           ELSE 100          -- free and any legacy/unknown tier: metered at the free allowance
         END;
$$;


--
-- Name: track_event(uuid, text, text, text, integer, jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.track_event(p_session_id uuid, p_event_type text, p_event_action text, p_book_id text DEFAULT NULL::text, p_chapter_index integer DEFAULT NULL::integer, p_metadata jsonb DEFAULT '{}'::jsonb) RETURNS uuid
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare
  v_event_id uuid;
begin
  insert into public.events (user_id, session_id, event_type, event_action, book_id, chapter_index, metadata)
  values (auth.uid(), p_session_id, p_event_type, p_event_action, p_book_id, p_chapter_index, p_metadata)
  returning id into v_event_id;

  update public.profiles set last_active_at = now() where id = auth.uid();

  return v_event_id;
end;
$$;


--
-- Name: track_generation(text, integer, text, text, text, integer, integer, numeric, text, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.track_generation(p_book_id text, p_chapter_index integer, p_module text, p_provider text, p_model text, p_input_chars integer, p_output_duration_ms integer DEFAULT NULL::integer, p_estimated_cost numeric DEFAULT NULL::numeric, p_status text DEFAULT 'success'::text, p_error_message text DEFAULT NULL::text) RETURNS uuid
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare
  v_gen_id uuid;
begin
  insert into public.generations (
    user_id, book_id, chapter_index, module, provider, model,
    input_chars, output_duration_ms, estimated_cost_usd, status, error_message
  ) values (
    auth.uid(), p_book_id, p_chapter_index, p_module, p_provider, p_model,
    p_input_chars, p_output_duration_ms, p_estimated_cost, p_status, p_error_message
  )
  returning id into v_gen_id;

  return v_gen_id;
end;
$$;


--
-- Name: trg_referral_engagement(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.trg_referral_engagement() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
  -- Never let referral logic break usage logging: swallow any error.
  BEGIN
    PERFORM award_referral_on_engagement(NEW.user_id);
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bonus_credits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bonus_credits (
    user_id uuid NOT NULL,
    balance integer DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: credit_ledger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_ledger (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    delta integer NOT NULL,
    type text NOT NULL,
    reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: credit_ledger_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_ledger ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.credit_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: credit_pack_purchases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_pack_purchases (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    stripe_session_id text,
    pack_type text NOT NULL,
    credits integer NOT NULL,
    amount_cents integer NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: credit_pack_purchases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_pack_purchases ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.credit_pack_purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    session_id uuid,
    event_type text NOT NULL,
    event_action text NOT NULL,
    book_id text,
    chapter_index integer,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE events; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.events IS 'Append-only event log for all user actions';


--
-- Name: generations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    book_id text,
    chapter_index integer,
    module text NOT NULL,
    provider text,
    model text,
    input_chars integer,
    output_duration_ms integer,
    estimated_cost_usd numeric(10,6),
    status text DEFAULT 'success'::text NOT NULL,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT generations_module_check CHECK ((module = ANY (ARRAY['voice'::text, 'podcast'::text, 'video'::text, 'visualizer'::text, 'mind_map'::text]))),
    CONSTRAINT generations_status_check CHECK ((status = ANY (ARRAY['success'::text, 'failed'::text, 'canceled'::text])))
);


--
-- Name: TABLE generations; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.generations IS 'Denormalized generation log for cost tracking and quota enforcement';


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    email text,
    display_name text,
    avatar_url text,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_active_at timestamp with time zone DEFAULT now() NOT NULL,
    total_books_uploaded integer DEFAULT 0 NOT NULL,
    total_generations integer DEFAULT 0 NOT NULL
);


--
-- Name: TABLE profiles; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.profiles IS 'Extended user profile, linked 1:1 to auth.users';


--
-- Name: referral_clicks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referral_clicks (
    id bigint NOT NULL,
    referrer_id uuid NOT NULL,
    visitor_hash text NOT NULL,
    credited boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: referral_clicks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referral_clicks ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.referral_clicks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referral_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referral_codes (
    user_id uuid NOT NULL,
    code text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: referral_signups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referral_signups (
    id bigint NOT NULL,
    referrer_id uuid NOT NULL,
    referred_user_id uuid NOT NULL,
    activated boolean DEFAULT false,
    referrer_credited boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    referred_ip_hash text
);


--
-- Name: referral_signups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referral_signups ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.referral_signups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    duration_seconds integer,
    device_type text,
    os text,
    browser text,
    screen_width integer,
    screen_height integer,
    referrer text,
    is_pwa boolean DEFAULT false,
    CONSTRAINT sessions_device_type_check CHECK ((device_type = ANY (ARRAY['mobile'::text, 'tablet'::text, 'desktop'::text])))
);


--
-- Name: TABLE sessions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.sessions IS 'Visit sessions for engagement metrics';


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    stripe_customer_id text,
    stripe_subscription_id text,
    tier text DEFAULT 'free'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    stripe_price_id text,
    cancel_at_period_end boolean DEFAULT false NOT NULL,
    pack_credits_balance integer DEFAULT 0,
    pack_credits_purchased integer DEFAULT 0,
    CONSTRAINT subscriptions_status_check CHECK ((status = ANY (ARRAY['active'::text, 'canceled'::text, 'past_due'::text, 'trialing'::text, 'incomplete'::text]))),
    CONSTRAINT subscriptions_tier_check CHECK ((tier = ANY (ARRAY['free'::text, 'pro'::text, 'byok'::text, 'unlimited'::text])))
);


--
-- Name: TABLE subscriptions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.subscriptions IS 'Stripe subscription state, writable only via service role / webhooks';


--
-- Name: usage_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usage_logs (
    id bigint NOT NULL,
    user_id uuid,
    action text,
    tokens_used integer DEFAULT 0,
    cost_cents integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    input_tokens integer DEFAULT 0,
    output_tokens integer DEFAULT 0,
    credits_cost integer DEFAULT 0,
    usage_id uuid,
    model text,
    book_title text,
    session_id text,
    CONSTRAINT usage_logs_credits_cost_nonneg CHECK ((credits_cost >= 0))
);


--
-- Name: usage_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usage_logs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.usage_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_books (
    id text NOT NULL,
    user_id uuid NOT NULL,
    title text NOT NULL,
    author text DEFAULT 'Unknown Author'::text NOT NULL,
    chapters jsonb DEFAULT '[]'::jsonb NOT NULL,
    bookmarks jsonb DEFAULT '[]'::jsonb NOT NULL,
    content text,
    mime_type text DEFAULT 'text/plain'::text NOT NULL,
    is_text boolean DEFAULT true NOT NULL,
    upload_date bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    pdf_figures jsonb,
    pdf_outline jsonb
);


--
-- Name: user_notebook; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_notebook (
    id text NOT NULL,
    user_id uuid NOT NULL,
    text text NOT NULL,
    type text NOT NULL,
    definition text,
    "timestamp" bigint NOT NULL,
    source_chapter text,
    book_title text,
    book_author text,
    comment text,
    context_source text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_notebook_type_check CHECK ((type = ANY (ARRAY['word'::text, 'phrase'::text, 'sentence'::text])))
);


--
-- Name: user_reading_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_reading_state (
    user_id uuid NOT NULL,
    book_id text NOT NULL,
    active_chapter_id integer,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_settings (
    user_id uuid NOT NULL,
    gemini_key text,
    openrouter_key text,
    target_language text DEFAULT 'Original'::text,
    highlight_color text DEFAULT 'indigo'::text,
    text_size text DEFAULT 'base'::text,
    line_height text DEFAULT 'normal'::text,
    letter_spacing text DEFAULT 'normal'::text,
    font text DEFAULT 'Inter'::text,
    updated_at timestamp with time zone DEFAULT now(),
    image_model text,
    video_model text,
    llm_model text,
    tts_model text
);


--
-- Name: user_synced_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_synced_files (
    user_id uuid NOT NULL,
    file_key text NOT NULL,
    filename text,
    file_type text,
    size bigint DEFAULT 0,
    book_id text,
    book_title text,
    synced_at bigint
);


--
-- Name: v_daily_active_users; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_daily_active_users AS
 SELECT (date_trunc('day'::text, created_at))::date AS day,
    count(DISTINCT user_id) AS dau
   FROM public.events
  WHERE (user_id IS NOT NULL)
  GROUP BY ((date_trunc('day'::text, created_at))::date)
  ORDER BY ((date_trunc('day'::text, created_at))::date) DESC;


--
-- Name: v_daily_events_by_module; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_daily_events_by_module AS
 SELECT (date_trunc('day'::text, created_at))::date AS day,
    event_type,
    event_action,
    count(*) AS event_count,
    count(DISTINCT user_id) AS unique_users
   FROM public.events
  GROUP BY ((date_trunc('day'::text, created_at))::date), event_type, event_action
  ORDER BY ((date_trunc('day'::text, created_at))::date) DESC, (count(*)) DESC;


--
-- Name: v_feature_adoption; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_feature_adoption AS
 SELECT user_id,
    array_agg(DISTINCT module) AS modules_used,
    count(DISTINCT module) AS module_count,
    min(created_at) AS first_generation,
    max(created_at) AS last_generation
   FROM public.generations
  WHERE (status = 'success'::text)
  GROUP BY user_id;


--
-- Name: v_generation_stats; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_generation_stats AS
 SELECT module,
    status,
    count(*) AS total,
    avg(input_chars) AS avg_input_chars,
    avg(output_duration_ms) AS avg_output_ms,
    sum(estimated_cost_usd) AS total_cost_usd
   FROM public.generations
  GROUP BY module, status
  ORDER BY (count(*)) DESC;


--
-- Name: v_user_engagement; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_user_engagement AS
 SELECT p.id AS user_id,
    p.email,
    p.first_seen_at,
    p.last_active_at,
    p.total_books_uploaded,
    p.total_generations,
    count(DISTINCT s.id) AS total_sessions,
    COALESCE(avg(s.duration_seconds), (0)::numeric) AS avg_session_duration,
    count(DISTINCT e.id) AS total_events,
    max(e.created_at) AS last_event_at
   FROM ((public.profiles p
     LEFT JOIN public.sessions s ON ((s.user_id = p.id)))
     LEFT JOIN public.events e ON ((e.user_id = p.id)))
  GROUP BY p.id, p.email, p.first_seen_at, p.last_active_at, p.total_books_uploaded, p.total_generations;


--
-- Name: v_user_funnel; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_user_funnel AS
 SELECT id AS user_id,
    first_seen_at AS signed_up_at,
    ( SELECT min(to_timestamp((((ub.upload_date)::numeric / 1000.0))::double precision)) AS min
           FROM public.user_books ub
          WHERE (ub.user_id = p.id)) AS first_upload_at,
    ( SELECT min(g.created_at) AS min
           FROM public.generations g
          WHERE ((g.user_id = p.id) AND (g.status = 'success'::text))) AS first_generation_at,
    ( SELECT min(e.created_at) AS min
           FROM public.events e
          WHERE ((e.user_id = p.id) AND (e.event_type = 'share'::text))) AS first_share_at
   FROM public.profiles p;


--
-- Name: bonus_credits bonus_credits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_credits
    ADD CONSTRAINT bonus_credits_pkey PRIMARY KEY (user_id);


--
-- Name: credit_ledger credit_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_ledger
    ADD CONSTRAINT credit_ledger_pkey PRIMARY KEY (id);


--
-- Name: credit_pack_purchases credit_pack_purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_pack_purchases
    ADD CONSTRAINT credit_pack_purchases_pkey PRIMARY KEY (id);


--
-- Name: credit_pack_purchases credit_pack_purchases_stripe_session_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_pack_purchases
    ADD CONSTRAINT credit_pack_purchases_stripe_session_id_key UNIQUE (stripe_session_id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: generations generations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT generations_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: referral_clicks referral_clicks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_clicks
    ADD CONSTRAINT referral_clicks_pkey PRIMARY KEY (id);


--
-- Name: referral_clicks referral_clicks_referrer_id_visitor_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_clicks
    ADD CONSTRAINT referral_clicks_referrer_id_visitor_hash_key UNIQUE (referrer_id, visitor_hash);


--
-- Name: referral_codes referral_codes_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_codes
    ADD CONSTRAINT referral_codes_code_key UNIQUE (code);


--
-- Name: referral_codes referral_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_codes
    ADD CONSTRAINT referral_codes_pkey PRIMARY KEY (user_id);


--
-- Name: referral_signups referral_signups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_signups
    ADD CONSTRAINT referral_signups_pkey PRIMARY KEY (id);


--
-- Name: referral_signups referral_signups_referred_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_signups
    ADD CONSTRAINT referral_signups_referred_user_id_key UNIQUE (referred_user_id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_stripe_subscription_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_stripe_subscription_id_key UNIQUE (stripe_subscription_id);


--
-- Name: usage_logs usage_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usage_logs
    ADD CONSTRAINT usage_logs_pkey PRIMARY KEY (id);


--
-- Name: user_books user_books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_books
    ADD CONSTRAINT user_books_pkey PRIMARY KEY (id, user_id);


--
-- Name: user_notebook user_notebook_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notebook
    ADD CONSTRAINT user_notebook_pkey PRIMARY KEY (id, user_id);


--
-- Name: user_reading_state user_reading_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reading_state
    ADD CONSTRAINT user_reading_state_pkey PRIMARY KEY (user_id, book_id);


--
-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id);


--
-- Name: user_synced_files user_synced_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_synced_files
    ADD CONSTRAINT user_synced_files_pkey PRIMARY KEY (user_id, file_key);


--
-- Name: idx_credit_ledger_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_credit_ledger_user ON public.credit_ledger USING btree (user_id, created_at DESC);


--
-- Name: idx_credit_pack_purchases_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_credit_pack_purchases_user ON public.credit_pack_purchases USING btree (user_id);


--
-- Name: idx_events_book; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_book ON public.events USING btree (book_id) WHERE (book_id IS NOT NULL);


--
-- Name: idx_events_created_brin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_created_brin ON public.events USING brin (created_at);


--
-- Name: idx_events_metadata; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_metadata ON public.events USING gin (metadata);


--
-- Name: idx_events_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_session ON public.events USING btree (session_id);


--
-- Name: idx_events_type_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_type_action ON public.events USING btree (event_type, event_action, created_at DESC);


--
-- Name: idx_events_user_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_user_time ON public.events USING btree (user_id, created_at DESC);


--
-- Name: idx_generations_book; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generations_book ON public.generations USING btree (book_id) WHERE (book_id IS NOT NULL);


--
-- Name: idx_generations_module; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generations_module ON public.generations USING btree (module, created_at DESC);


--
-- Name: idx_generations_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generations_user ON public.generations USING btree (user_id, created_at DESC);


--
-- Name: idx_referral_clicks_referrer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_referral_clicks_referrer ON public.referral_clicks USING btree (referrer_id);


--
-- Name: idx_referral_signups_referrer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_referral_signups_referrer ON public.referral_signups USING btree (referrer_id);


--
-- Name: idx_sessions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_user ON public.sessions USING btree (user_id, started_at DESC);


--
-- Name: idx_subscriptions_stripe; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscriptions_stripe ON public.subscriptions USING btree (stripe_customer_id);


--
-- Name: idx_subscriptions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscriptions_user ON public.subscriptions USING btree (user_id);


--
-- Name: idx_user_books_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_books_user ON public.user_books USING btree (user_id);


--
-- Name: idx_user_notebook_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_notebook_user ON public.user_notebook USING btree (user_id);


--
-- Name: usage_logs_usage_id_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX usage_logs_usage_id_key ON public.usage_logs USING btree (usage_id);


--
-- Name: generations on_generation_created; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_generation_created AFTER INSERT ON public.generations FOR EACH ROW EXECUTE FUNCTION public.increment_generation_count();


--
-- Name: subscriptions subscriptions_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER subscriptions_updated_at BEFORE UPDATE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: usage_logs trg_deplete_wallet; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_deplete_wallet AFTER INSERT ON public.usage_logs FOR EACH ROW EXECUTE FUNCTION public.deplete_wallet_on_usage();


--
-- Name: usage_logs trg_referral_engagement; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_referral_engagement AFTER INSERT ON public.usage_logs FOR EACH ROW EXECUTE FUNCTION public.trg_referral_engagement();


--
-- Name: user_books user_books_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER user_books_updated_at BEFORE UPDATE ON public.user_books FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: user_notebook user_notebook_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER user_notebook_updated_at BEFORE UPDATE ON public.user_notebook FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: user_reading_state user_reading_state_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER user_reading_state_updated_at BEFORE UPDATE ON public.user_reading_state FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: bonus_credits bonus_credits_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_credits
    ADD CONSTRAINT bonus_credits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: credit_ledger credit_ledger_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_ledger
    ADD CONSTRAINT credit_ledger_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: credit_pack_purchases credit_pack_purchases_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_pack_purchases
    ADD CONSTRAINT credit_pack_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: events events_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE SET NULL;


--
-- Name: events events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;


--
-- Name: generations generations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT generations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;


--
-- Name: profiles profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: referral_clicks referral_clicks_referrer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_clicks
    ADD CONSTRAINT referral_clicks_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES auth.users(id);


--
-- Name: referral_codes referral_codes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_codes
    ADD CONSTRAINT referral_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: referral_signups referral_signups_referred_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_signups
    ADD CONSTRAINT referral_signups_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES auth.users(id);


--
-- Name: referral_signups referral_signups_referrer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_signups
    ADD CONSTRAINT referral_signups_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES auth.users(id);


--
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;


--
-- Name: subscriptions subscriptions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;


--
-- Name: usage_logs usage_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usage_logs
    ADD CONSTRAINT usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: user_books user_books_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_books
    ADD CONSTRAINT user_books_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: user_notebook user_notebook_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notebook
    ADD CONSTRAINT user_notebook_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: user_reading_state user_reading_state_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reading_state
    ADD CONSTRAINT user_reading_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: user_settings user_settings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: user_synced_files user_synced_files_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_synced_files
    ADD CONSTRAINT user_synced_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: events Users can insert own events; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can insert own events" ON public.events FOR INSERT WITH CHECK ((auth.uid() = user_id));


--
-- Name: generations Users can insert own generations; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can insert own generations" ON public.generations FOR INSERT WITH CHECK ((auth.uid() = user_id));


--
-- Name: sessions Users can insert own sessions; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can insert own sessions" ON public.sessions FOR INSERT WITH CHECK ((auth.uid() = user_id));


--
-- Name: user_books Users can manage own books; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can manage own books" ON public.user_books USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: user_notebook Users can manage own notebook; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can manage own notebook" ON public.user_notebook USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: user_reading_state Users can manage own reading state; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can manage own reading state" ON public.user_reading_state USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: profiles Users can update own profile; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));


--
-- Name: sessions Users can update own sessions; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can update own sessions" ON public.sessions FOR UPDATE USING ((auth.uid() = user_id));


--
-- Name: generations Users can view own generations; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can view own generations" ON public.generations FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: profiles Users can view own profile; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING ((auth.uid() = id));


--
-- Name: sessions Users can view own sessions; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can view own sessions" ON public.sessions FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: subscriptions Users can view own subscription; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can view own subscription" ON public.subscriptions FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: usage_logs Users insert own zero-credit logs; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users insert own zero-credit logs" ON public.usage_logs FOR INSERT WITH CHECK (((auth.uid() = user_id) AND (credits_cost = 0)));


--
-- Name: user_settings Users manage own settings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users manage own settings" ON public.user_settings USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: user_synced_files Users manage own synced files; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users manage own synced files" ON public.user_synced_files USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: bonus_credits Users read own bonus credits; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users read own bonus credits" ON public.bonus_credits FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: credit_ledger Users read own credit ledger; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users read own credit ledger" ON public.credit_ledger FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: usage_logs Users read own logs; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users read own logs" ON public.usage_logs FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: credit_pack_purchases Users read own pack purchases; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users read own pack purchases" ON public.credit_pack_purchases FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: referral_clicks Users read own referral clicks; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users read own referral clicks" ON public.referral_clicks FOR SELECT USING ((auth.uid() = referrer_id));


--
-- Name: referral_codes Users read own referral code; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users read own referral code" ON public.referral_codes FOR SELECT USING ((auth.uid() = user_id));


--
-- Name: referral_signups Users read own referral signups; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users read own referral signups" ON public.referral_signups FOR SELECT USING ((auth.uid() = referrer_id));


--
-- Name: bonus_credits; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.bonus_credits ENABLE ROW LEVEL SECURITY;

--
-- Name: credit_ledger; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.credit_ledger ENABLE ROW LEVEL SECURITY;

--
-- Name: credit_pack_purchases; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.credit_pack_purchases ENABLE ROW LEVEL SECURITY;

--
-- Name: events; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

--
-- Name: generations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.generations ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: referral_clicks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.referral_clicks ENABLE ROW LEVEL SECURITY;

--
-- Name: referral_codes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;

--
-- Name: referral_signups; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.referral_signups ENABLE ROW LEVEL SECURITY;

--
-- Name: sessions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

--
-- Name: subscriptions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

--
-- Name: usage_logs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;

--
-- Name: user_books; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_books ENABLE ROW LEVEL SECURITY;

--
-- Name: user_notebook; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_notebook ENABLE ROW LEVEL SECURITY;

--
-- Name: user_reading_state; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_reading_state ENABLE ROW LEVEL SECURITY;

--
-- Name: user_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: user_synced_files; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_synced_files ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: FUNCTION add_bonus_credits(p_user_id uuid, p_credits integer); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.add_bonus_credits(p_user_id uuid, p_credits integer) FROM PUBLIC;
GRANT ALL ON FUNCTION public.add_bonus_credits(p_user_id uuid, p_credits integer) TO service_role;


--
-- Name: FUNCTION add_pack_credits(p_user_id uuid, p_credits integer); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.add_pack_credits(p_user_id uuid, p_credits integer) FROM PUBLIC;
GRANT ALL ON FUNCTION public.add_pack_credits(p_user_id uuid, p_credits integer) TO service_role;


--
-- Name: FUNCTION award_referral_on_engagement(p_referred uuid); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.award_referral_on_engagement(p_referred uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.award_referral_on_engagement(p_referred uuid) TO service_role;


--
-- Name: FUNCTION credit_period_start(p_user_id uuid, p_tier text, p_sub_start timestamp with time zone); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.credit_period_start(p_user_id uuid, p_tier text, p_sub_start timestamp with time zone) TO anon;
GRANT ALL ON FUNCTION public.credit_period_start(p_user_id uuid, p_tier text, p_sub_start timestamp with time zone) TO authenticated;
GRANT ALL ON FUNCTION public.credit_period_start(p_user_id uuid, p_tier text, p_sub_start timestamp with time zone) TO service_role;


--
-- Name: FUNCTION deplete_wallet_on_usage(); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.deplete_wallet_on_usage() TO anon;
GRANT ALL ON FUNCTION public.deplete_wallet_on_usage() TO authenticated;
GRANT ALL ON FUNCTION public.deplete_wallet_on_usage() TO service_role;


--
-- Name: FUNCTION end_session(p_session_id uuid); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.end_session(p_session_id uuid) TO anon;
GRANT ALL ON FUNCTION public.end_session(p_session_id uuid) TO authenticated;
GRANT ALL ON FUNCTION public.end_session(p_session_id uuid) TO service_role;


--
-- Name: FUNCTION get_or_create_referral_code(p_user_id uuid); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.get_or_create_referral_code(p_user_id uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_or_create_referral_code(p_user_id uuid) TO service_role;


--
-- Name: FUNCTION get_referral_stats(p_user_id uuid); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.get_referral_stats(p_user_id uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_referral_stats(p_user_id uuid) TO service_role;


--
-- Name: FUNCTION get_user_credits(p_user_id uuid); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.get_user_credits(p_user_id uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_user_credits(p_user_id uuid) TO service_role;


--
-- Name: FUNCTION get_user_tier_and_usage(p_user_id uuid); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.get_user_tier_and_usage(p_user_id uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_user_tier_and_usage(p_user_id uuid) TO service_role;


--
-- Name: FUNCTION handle_new_user(); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.handle_new_user() TO anon;
GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;
GRANT ALL ON FUNCTION public.handle_new_user() TO service_role;


--
-- Name: FUNCTION increment_generation_count(); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.increment_generation_count() TO anon;
GRANT ALL ON FUNCTION public.increment_generation_count() TO authenticated;
GRANT ALL ON FUNCTION public.increment_generation_count() TO service_role;


--
-- Name: FUNCTION normalize_email(e text); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.normalize_email(e text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.normalize_email(e text) TO service_role;


--
-- Name: FUNCTION set_updated_at(); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.set_updated_at() TO anon;
GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;


--
-- Name: FUNCTION start_session(p_device_type text, p_os text, p_browser text, p_screen_width integer, p_screen_height integer, p_referrer text, p_is_pwa boolean); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.start_session(p_device_type text, p_os text, p_browser text, p_screen_width integer, p_screen_height integer, p_referrer text, p_is_pwa boolean) TO anon;
GRANT ALL ON FUNCTION public.start_session(p_device_type text, p_os text, p_browser text, p_screen_width integer, p_screen_height integer, p_referrer text, p_is_pwa boolean) TO authenticated;
GRANT ALL ON FUNCTION public.start_session(p_device_type text, p_os text, p_browser text, p_screen_width integer, p_screen_height integer, p_referrer text, p_is_pwa boolean) TO service_role;


--
-- Name: FUNCTION tier_monthly_credits(p_tier text); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.tier_monthly_credits(p_tier text) TO anon;
GRANT ALL ON FUNCTION public.tier_monthly_credits(p_tier text) TO authenticated;
GRANT ALL ON FUNCTION public.tier_monthly_credits(p_tier text) TO service_role;


--
-- Name: FUNCTION track_event(p_session_id uuid, p_event_type text, p_event_action text, p_book_id text, p_chapter_index integer, p_metadata jsonb); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.track_event(p_session_id uuid, p_event_type text, p_event_action text, p_book_id text, p_chapter_index integer, p_metadata jsonb) TO anon;
GRANT ALL ON FUNCTION public.track_event(p_session_id uuid, p_event_type text, p_event_action text, p_book_id text, p_chapter_index integer, p_metadata jsonb) TO authenticated;
GRANT ALL ON FUNCTION public.track_event(p_session_id uuid, p_event_type text, p_event_action text, p_book_id text, p_chapter_index integer, p_metadata jsonb) TO service_role;


--
-- Name: FUNCTION track_generation(p_book_id text, p_chapter_index integer, p_module text, p_provider text, p_model text, p_input_chars integer, p_output_duration_ms integer, p_estimated_cost numeric, p_status text, p_error_message text); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.track_generation(p_book_id text, p_chapter_index integer, p_module text, p_provider text, p_model text, p_input_chars integer, p_output_duration_ms integer, p_estimated_cost numeric, p_status text, p_error_message text) TO anon;
GRANT ALL ON FUNCTION public.track_generation(p_book_id text, p_chapter_index integer, p_module text, p_provider text, p_model text, p_input_chars integer, p_output_duration_ms integer, p_estimated_cost numeric, p_status text, p_error_message text) TO authenticated;
GRANT ALL ON FUNCTION public.track_generation(p_book_id text, p_chapter_index integer, p_module text, p_provider text, p_model text, p_input_chars integer, p_output_duration_ms integer, p_estimated_cost numeric, p_status text, p_error_message text) TO service_role;


--
-- Name: FUNCTION trg_referral_engagement(); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.trg_referral_engagement() TO anon;
GRANT ALL ON FUNCTION public.trg_referral_engagement() TO authenticated;
GRANT ALL ON FUNCTION public.trg_referral_engagement() TO service_role;


--
-- Name: TABLE bonus_credits; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.bonus_credits TO anon;
GRANT ALL ON TABLE public.bonus_credits TO authenticated;
GRANT ALL ON TABLE public.bonus_credits TO service_role;


--
-- Name: TABLE credit_ledger; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.credit_ledger TO anon;
GRANT ALL ON TABLE public.credit_ledger TO authenticated;
GRANT ALL ON TABLE public.credit_ledger TO service_role;


--
-- Name: SEQUENCE credit_ledger_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.credit_ledger_id_seq TO anon;
GRANT ALL ON SEQUENCE public.credit_ledger_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.credit_ledger_id_seq TO service_role;


--
-- Name: TABLE credit_pack_purchases; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.credit_pack_purchases TO anon;
GRANT ALL ON TABLE public.credit_pack_purchases TO authenticated;
GRANT ALL ON TABLE public.credit_pack_purchases TO service_role;


--
-- Name: SEQUENCE credit_pack_purchases_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.credit_pack_purchases_id_seq TO anon;
GRANT ALL ON SEQUENCE public.credit_pack_purchases_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.credit_pack_purchases_id_seq TO service_role;


--
-- Name: TABLE events; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.events TO anon;
GRANT ALL ON TABLE public.events TO authenticated;
GRANT ALL ON TABLE public.events TO service_role;


--
-- Name: TABLE generations; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.generations TO anon;
GRANT ALL ON TABLE public.generations TO authenticated;
GRANT ALL ON TABLE public.generations TO service_role;


--
-- Name: TABLE profiles; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.profiles TO anon;
GRANT ALL ON TABLE public.profiles TO authenticated;
GRANT ALL ON TABLE public.profiles TO service_role;


--
-- Name: TABLE referral_clicks; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.referral_clicks TO anon;
GRANT ALL ON TABLE public.referral_clicks TO authenticated;
GRANT ALL ON TABLE public.referral_clicks TO service_role;


--
-- Name: SEQUENCE referral_clicks_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.referral_clicks_id_seq TO anon;
GRANT ALL ON SEQUENCE public.referral_clicks_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.referral_clicks_id_seq TO service_role;


--
-- Name: TABLE referral_codes; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.referral_codes TO anon;
GRANT ALL ON TABLE public.referral_codes TO authenticated;
GRANT ALL ON TABLE public.referral_codes TO service_role;


--
-- Name: TABLE referral_signups; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.referral_signups TO anon;
GRANT ALL ON TABLE public.referral_signups TO authenticated;
GRANT ALL ON TABLE public.referral_signups TO service_role;


--
-- Name: SEQUENCE referral_signups_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.referral_signups_id_seq TO anon;
GRANT ALL ON SEQUENCE public.referral_signups_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.referral_signups_id_seq TO service_role;


--
-- Name: TABLE sessions; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.sessions TO anon;
GRANT ALL ON TABLE public.sessions TO authenticated;
GRANT ALL ON TABLE public.sessions TO service_role;


--
-- Name: TABLE subscriptions; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.subscriptions TO anon;
GRANT ALL ON TABLE public.subscriptions TO authenticated;
GRANT ALL ON TABLE public.subscriptions TO service_role;


--
-- Name: TABLE usage_logs; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.usage_logs TO anon;
GRANT ALL ON TABLE public.usage_logs TO authenticated;
GRANT ALL ON TABLE public.usage_logs TO service_role;


--
-- Name: SEQUENCE usage_logs_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.usage_logs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.usage_logs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.usage_logs_id_seq TO service_role;


--
-- Name: TABLE user_books; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.user_books TO anon;
GRANT ALL ON TABLE public.user_books TO authenticated;
GRANT ALL ON TABLE public.user_books TO service_role;


--
-- Name: TABLE user_notebook; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.user_notebook TO anon;
GRANT ALL ON TABLE public.user_notebook TO authenticated;
GRANT ALL ON TABLE public.user_notebook TO service_role;


--
-- Name: TABLE user_reading_state; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.user_reading_state TO anon;
GRANT ALL ON TABLE public.user_reading_state TO authenticated;
GRANT ALL ON TABLE public.user_reading_state TO service_role;


--
-- Name: TABLE user_settings; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.user_settings TO anon;
GRANT ALL ON TABLE public.user_settings TO authenticated;
GRANT ALL ON TABLE public.user_settings TO service_role;


--
-- Name: TABLE user_synced_files; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.user_synced_files TO anon;
GRANT ALL ON TABLE public.user_synced_files TO authenticated;
GRANT ALL ON TABLE public.user_synced_files TO service_role;


--
-- Name: TABLE v_daily_active_users; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.v_daily_active_users TO anon;
GRANT ALL ON TABLE public.v_daily_active_users TO authenticated;
GRANT ALL ON TABLE public.v_daily_active_users TO service_role;


--
-- Name: TABLE v_daily_events_by_module; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.v_daily_events_by_module TO anon;
GRANT ALL ON TABLE public.v_daily_events_by_module TO authenticated;
GRANT ALL ON TABLE public.v_daily_events_by_module TO service_role;


--
-- Name: TABLE v_feature_adoption; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.v_feature_adoption TO anon;
GRANT ALL ON TABLE public.v_feature_adoption TO authenticated;
GRANT ALL ON TABLE public.v_feature_adoption TO service_role;


--
-- Name: TABLE v_generation_stats; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.v_generation_stats TO anon;
GRANT ALL ON TABLE public.v_generation_stats TO authenticated;
GRANT ALL ON TABLE public.v_generation_stats TO service_role;


--
-- Name: TABLE v_user_engagement; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.v_user_engagement TO anon;
GRANT ALL ON TABLE public.v_user_engagement TO authenticated;
GRANT ALL ON TABLE public.v_user_engagement TO service_role;


--
-- Name: TABLE v_user_funnel; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.v_user_funnel TO anon;
GRANT ALL ON TABLE public.v_user_funnel TO authenticated;
GRANT ALL ON TABLE public.v_user_funnel TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--
